# Generated by Django 4.0.5 on 2022-06-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trabjadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(max_length=10, verbose_name='Rut')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
            ],
        ),
        migrations.DeleteModel(
            name='tarea',
        ),
    ]
