# Generated by Django 4.0.5 on 2022-06-26 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_trabjadores_delete_tarea'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trabjadores',
            new_name='Trabajadores',
        ),
    ]
