# Generated by Django 4.0.5 on 2022-06-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0004_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idprof', models.CharField(max_length=100, verbose_name='Id')),
                ('nombre_prof', models.CharField(max_length=100, verbose_name='Nombre Profesión')),
            ],
        ),
    ]
