# Generated by Django 4.0.5 on 2022-06-27 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0005_profesion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='rut',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(default='Some String', max_length=10, verbose_name='nombre usuario'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=50, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre completo'),
        ),
    ]
