# Generated by Django 4.0.5 on 2022-06-27 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0006_remove_usuarios_apellido_remove_usuarios_rut_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='nombre_usuario',
            field=models.CharField(default='Some String', max_length=10, verbose_name='Usuario'),
        ),
    ]
