# Generated by Django 4.0.5 on 2022-06-27 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0007_alter_usuarios_nombre_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre_usuario',
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.CharField(max_length=100, verbose_name='Email'),
        ),
    ]
