# Generated by Django 4.0.5 on 2022-06-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0010_comunas_regiones_tipo_centro_centros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
