# Generated by Django 4.0.5 on 2022-06-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0011_alter_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajadores',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
