# Generated by Django 4.0.5 on 2022-07-01 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0012_alter_trabajadores_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='user',
            new_name='apelllidos_usu',
        ),
    ]
