# Generated by Django 4.0.5 on 2022-07-01 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0013_rename_user_usuarios_apelllidos_usu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='apelllidos_usu',
            field=models.CharField(max_length=100, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='contrasena',
            field=models.CharField(max_length=10, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuarios',
            name='nombre_com',
            field=models.CharField(max_length=100, verbose_name='Nombre completo'),
        ),
    ]
