# Generated by Django 4.0.5 on 2022-07-02 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0015_remove_profesion_idprof'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajadores',
            name='profesion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestor.profesion'),
        ),
    ]
