# Generated by Django 4.0.5 on 2022-11-28 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0016_trabajadores_profesion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tip_especi', models.CharField(max_length=100, verbose_name='Tipo especialidad')),
            ],
        ),
    ]
